const data = {
  products: [
    {
      name: 'Casinha de cachorro',
      slug: 'casinha-cachorro',
      category: 'Casa',
      image: '/images/casinha-cao.jpg',
      price: 80,
      brand: 'Oui',
      ratting: 4.2,
      numReviews: 3,
      countInStock: 4,
      description: 'Casinha para cães. Muito grande',
    },
    {
      name: 'Casinha de hamister',
      slug: 'casinha-hamister',
      category: 'Casa',
      image: '/images/casinha-hamister.jpg',
      price: 20,
      brand: 'Oui',
      ratting: 4.5,
      numReviews: 10,
      countInStock: 10,
      description: 'Casinha para hamister. Com brinquedo',
    },
    {
      name: 'Arranhador felino',
      slug: 'arranhador-felino',
      category: 'brinquedo',
      image: '/images/aranhador.jpg',
      price: 10,
      brand: 'Felino',
      ratting: 4.8,
      numReviews: 20,
      countInStock: 20,
      description: 'Arranhador felino para gatos. Muito divertido',
    },
    {
      name: 'Mordedor canino',
      slug: 'mordedor-canino',
      category: 'brinquedo',
      image: '/images/mordedor.jpg',
      price: 8,
      brand: 'Dog',
      ratting: 4.7,
      numReviews: 5,
      countInStock: 10,
      description: 'Mordedor para cães. Muito divertido',
    },
    {
      name: 'Porta ração',
      slug: 'porta-racao',
      category: 'brinquedo',
      image: '/images/bolinha-racao.jpg',
      price: 10,
      brand: 'Ração',
      ratting: 4.1,
      numReviews: 2,
      countInStock: 3,
      description: 'Porta ração. Muito divertido',
    },
    {
      name: 'Casa para felinos arranhar',
      slug: 'casa-felino-arranhador',
      category: 'brinquedo',
      image: '/images/casa-arranhadora.jpg',
      price: 50,
      brand: 'Cat',
      ratting: 4.5,
      numReviews: 4,
      countInStock: 3,
      description: 'Casinha para gatos arranhar. Muito divertido',
    },
  ],
};

export default data;
